import {
    IconAdjustmentsHorizontal,
    IconArrowDown,
    IconArrowLeft,
    IconArrowRight,
    IconArrowUp,
    IconArrowNarrowRight,
    IconArrowsUpDown,
    IconBoxMultipleFilled,
    IconBrandDiscordFilled,
    IconBrandFacebook,
    IconBrandInstagram,
    IconBrandX,
    IconCalendarWeek,
    IconLock,
    IconChalkboard,
    IconCheck,
    IconChevronDown,
    IconChevronLeft,
    IconChevronRight,
    IconChevronUp,
    IconChevronsDown,
    IconChevronsLeft,
    IconChevronsRight,
    IconChevronsUp,
    IconCircle,
    IconCircleCheck,
    IconCircleDashedCheck,
    IconCirclePlus,
    IconDeviceTvOld,
    IconDotsVertical,
    IconEye,
    IconEyeOff,
    IconHash,
    IconHelpCircle,
    IconKey,
    IconLibraryPhoto,
    IconMail,
    IconMenu,
    IconMenuDeep,
    IconMessagePlus,
    IconMessageQuestion,
    IconPhoneRinging,
    IconRosetteDiscountCheckFilled,
    IconSend,
    IconShield,
    IconSquareRounded,
    IconSquareRoundedCheck,
    IconStar,
    IconTrashX,
    IconTrophy,
    IconUserCog,
    IconUsersGroup,
    IconX,
    IconTimeDuration0,
    IconTimeDurationOff,
    IconSun,
    IconMoon,
    IconRings,
    IconBrandAppleFilled,
    IconSearch,
    IconFilter,
    IconArrowsSort,
    IconMap,
    IconCurrencyRupee,
    IconTimeline,
    IconTimelineEvent,
    IconClock,
    IconUserFilled,
    IconHomeFilled,
    IconBubbleTextFilled,
    IconBrandGooglePhotos,
    IconHeartHandshake,
    IconInfoTriangle,
    IconShieldLock,
    IconHeart,
    IconProgress,
    IconLogout,
    IconEdit,
    IconLogout2,
    IconPlus,
    IconMessage,
    IconUsers,
    IconBell,
    IconBellBolt,
    IconNotification,
    IconTrendingUp,
    IconTrendingDown,
    IconSortAscending,
    IconSortDescending,
    IconMapPin,
    IconPhone,
    IconLogin,
    IconUserX,
    IconLoader3,
    IconLoader2,
    IconLoader,
    IconBolt,
    IconQuote,
    IconBulb,
    IconBrandWhatsapp,
    IconBrandGoogle,
    IconRefresh,
    IconCalculator,
    IconMoodSmile,
    IconDownload,
    IconShare,
    IconArrowNarrowUp,
    IconArrowNarrowDown,
    IconArrowNarrowLeft,
    IconUserShield,
    IconPictureInPicture,
    IconMaximize,
    IconPawFilled,
    IconTree,
    IconMoneybagHeart,
    IconPhoneCalling,
    IconHeartPlus,
    IconBook,
    IconPaint,
    IconHandLoveYou,
    IconSTurnDown,
    IconExclamationMark,
    IconCreditCard,
    IconDeviceMobile,
    IconBuilding,
    IconMessage2,
    IconWallet,
    IconDeviceFloppy,
    IconFriends,
    IconBrandYoutube,
    IconTarget,
    IconGraph,
    IconOm,
    IconFlag,
    IconTicket,
} from "@tabler/icons-react";
import { FcGoogle } from "react-icons/fc";
import { FaFacebook, FaLinkedinIn } from "react-icons/fa";

export const Icons = {
    paw: IconPawFilled,
    exclamation: IconExclamationMark,
    heartHandshake: IconHeartHandshake,
    heartPulse: IconHeartPlus,
    message: IconMessage2,
    flag: IconFlag,
    bookOpen: IconBook,
    om: IconOm,
    people: IconUsers,
    tree: IconTree,
    friends: IconFriends,
    target: IconTarget,
    paintBrush: IconPaint,
    money: IconMoneybagHeart,
    handsHelping: IconHandLoveYou,
    graph: IconGraph,
    fireExtinguisher: IconSTurnDown,
    utensils: IconPictureInPicture,
    megaphone: IconPhoneCalling,

    arrowSort: IconArrowsSort,
    shieldCheck: IconUserShield,
    image: IconPictureInPicture,
    maximize: IconMaximize,
    arrowSortAsc: IconSortAscending,
    arrowSortDesc: IconSortDescending,
    whatsapp: IconBrandWhatsapp,
    youtube: IconBrandYoutube,
    download: IconDownload,
    arrowLeft: IconArrowLeft,
    twitter: IconBrandX,
    facebook: IconBrandFacebook,
    loginFacebook: FaFacebook,
    bolt: IconBolt,
    notification: IconNotification,
    discord: IconBrandDiscordFilled,
    instagram: IconBrandInstagram,
    share: IconShare,

    trendUp: IconTrendingUp,
    calculator: IconCalculator,
    simle: IconMoodSmile,
    trendDown: IconTrendingDown,
    linkedin: FaLinkedinIn,
    google: IconBrandGoogle,
    refresh: IconRefresh,
    loginGoogle: FcGoogle,
    apple: IconBrandAppleFilled,
    user: IconUserFilled,
    users: IconUsers,
    info: IconMessage,
    bell: IconBell,
    bellDot: IconBellBolt,
    home: IconHomeFilled,
    lock: IconLock,
    alertTriangle: IconInfoTriangle,
    heart: IconHeart,
    progress: IconProgress,
    logout: IconLogout,
    logout2: IconLogout2,

    faq: IconBubbleTextFilled,
    gallery: IconBrandGooglePhotos,
    donation: IconHeartHandshake,

    // Navigation
    menu: IconMenu,
    menuDeep: IconMenuDeep,
    arrowLeft: IconArrowLeft,
    arrowRight: IconArrowRight,
    arrowUp: IconArrowUp,
    arrowDown: IconArrowDown,
    chevronLeft: IconChevronLeft,
    chevronRight: IconChevronRight,
    chevronUp: IconChevronUp,
    chevronDown: IconChevronDown,
    chevronsLeft: IconChevronsLeft,
    chevronsRight: IconChevronsRight,
    chevronsUp: IconChevronsUp,
    chevronsDown: IconChevronsDown,
    arrowsUpDown: IconArrowsUpDown,
    moreOptions: IconDotsVertical,
    arrowsSort: IconArrowsSort,
    map: IconMap,
    rupees: IconCurrencyRupee,
    ticket: IconTicket,
    timelineEvent: IconTimelineEvent,
    timeline: IconTimeline,
    clock: IconClock,

    // UI Actions
    send: IconSend,
    delete: IconTrashX,
    x: IconX,
    plus: IconPlus,
    mail: IconMail,
    messageAdd: IconMessagePlus,
    settings: IconAdjustmentsHorizontal,
    key: IconKey,
    circleAdd: IconCirclePlus,
    edit: IconEdit,
    user: IconUserFilled,
    userX: IconUserX,
    mapPin: IconMapPin,
    phone: IconPhone,
    logIn: IconLogin,
    save: IconDeviceFloppy,

    // Status & Feedback
    verified: (
        <IconRosetteDiscountCheckFilled className="fill-blue-400" size={28} />
    ),
    verifiedBadge: (
        <IconRosetteDiscountCheckFilled className="fill-blue-400 text-black" />
    ),
    check: IconCheck,
    checkCircle: IconCircleCheck,
    dashedCheckCircle: IconCircleDashedCheck,
    squareUnchecked: IconSquareRounded,
    squareChecked: IconSquareRoundedCheck,
    circle: IconCircle,
    eye: IconEye,
    eyeOff: IconEyeOff,
    loader3: IconLoader3,
    loader2: IconLoader2,
    loader: IconLoader,

    // User & Groups
    userSettings: IconUserCog,
    userGroup: IconUsersGroup,

    // Features
    filter: IconFilter,
    search: IconSearch,
    star: IconStar,
    shield: IconShield,
    shieldLock: IconShieldLock,
    leaderboard: IconTrophy,
    mentor: IconChalkboard,
    calendar: IconCalendarWeek,
    contact: IconPhoneRinging,
    gallery: IconLibraryPhoto,
    media: IconDeviceTvOld,
    faq: IconMessageQuestion,
    blog: IconBoxMultipleFilled,
    wedding: IconRings,
    help: IconHelpCircle,
    hashtag: IconHash,
    sun: IconSun,
    arrowNarrowRight: IconArrowNarrowRight,
    arrowNarrowUp: IconArrowNarrowUp,
    arrowNarrowDown: IconArrowNarrowDown,
    arrowNarrowLeft: IconArrowNarrowLeft,
    moon: IconMoon,

    // Timer
    timer: IconTimeDuration0,
    timerOff: IconTimeDurationOff,
    lightbulb: IconBulb,
    quote: IconQuote,

    // Payment
    creditCard: IconCreditCard,
    smartphone: IconDeviceMobile,
    building: IconBuilding,
    wallet: IconWallet,
};
